Lesson4
Pekhov/TestGuru pull request #3
Opened 2018-11-01 10:18 UTC by Pekhov

2018-11-01 13:05 UTC, BubuntuClu requested changes

2018-11-01 13:05 UTC, BubuntuClu commented on app/models/test.rb
> +      where(category_id: Category.find_by(title: category).id).pluck(:title)
давай это реализуем через один запрос к БД? используй тут `join`, чтоб связаться с категориями

2018-11-01 13:05 UTC, BubuntuClu commented on db/migrate/20181031122844_create_user_histories.rb
> +    create_table :user_histories do |t|
как тебе название таблицы `users_tests`? обычно промежуточные таблицы называют по именам таблиц, которые в ней участвуют.
не понятно о каких историях тут идет речь

2018-11-01 13:05 UTC, BubuntuClu commented on db/migrate/20181031122844_create_user_histories.rb
> +      t.references :user
внешние ключи

2018-11-01 13:05 UTC, BubuntuClu commented on app/models/user.rb
> +    user_tests = UserHistory.where(user_id: self.id).pluck(:test_id)
тут тоже давай через один запрос к БД это сделаем.

2018-11-01 13:05 UTC, BubuntuClu commented on db/seeds.rb
> +Category.create(title: "Внедорожники")
можно результаты создания всех объектов поместить в массив, и дальше использовать его. Например, `categories = Category.create([{...}])`

`tests = Test.create([{..., category: categories[0]}, {...}])`
и т.д.

2018-11-02 12:27 UTC, BubuntuClu commented on app/models/test.rb
> +      joins(:category).where(categories: {title: category}).pluck(:title)
сортировки по убыванию не хватает

2018-11-02 12:27 UTC, BubuntuClu commented on app/models/test.rb
> +  has_many :user_tests
такая ассоциация здесь не подойдет. `has_many` другую структуру БД требует

2018-11-02 12:27 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :user_tests
такая ассоциация здесь не подойдет. `has_many` другую структуру БД требует

2018-11-02 12:27 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.joins(:user_tests).where(user_tests: {user_id: self.id}, tests: {level: level})
`self` можно опустить

2018-11-02 13:45 UTC, psylone approved these changes

2018-11-02 13:45 UTC, psylone commented on db/seeds.rb
> +CATEGORY_NAME.each do |name|
По факту, константа тебе здесь не нужна.

2018-11-02 13:45 UTC, psylone commented on db/seeds.rb
> +Question.create(body: "На загородной трассе вы встали в пробку. Выши действия?", test_id: 1)
Выше ты используешь массив `categories`, здесь тоже стоит использовать объекты вместо явных идентификаторов в атрибуте `test_id`.

2018-11-02 13:45 UTC, psylone commented on app/models/user.rb
> +    Test.joins(:user_tests).where(user_tests: {user_id: self.id}, tests: {level: level})
Также можно вызвать `where` 2 раза: `where(user_tests: { user_id: id }).where(level: level)`.

2018-11-15 07:38 UTC, merged

2018-11-15 20:58 UTC, BubuntuClu commented on db/migrate/20181026115753_create_answers.rb
> +      t.references :question, foreign_key: true
так миграции нельзя править. можно редактировать файл миграции только если ты его создал в этой ветки. любые другие изменения только через новую миграцию

2018-11-16 05:42 UTC, Pekhov commented on db/migrate/20181026115753_create_answers.rb
> +      t.references :question, foreign_key: true
Хорошо, учту