Lesson 5
Pekhov/TestGuru pull request #4
Opened 2018-11-15 07:57 UTC by Pekhov

2018-11-27 23:14 UTC, psylone requested changes
Нет ассоциаций для автора теста и тестов автора в моделях теста и пользователя соответственно.

2018-11-28 08:24 UTC, BubuntuClu requested changes

2018-11-28 08:24 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user
чем отличается `user` от `users`? надо нейминг сделать, который будет указывать на авторство

2018-11-28 08:24 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests
тут у тебя два одинаковых имени в ассоциациях, такое работать не будет

2018-11-29 12:00 UTC, psylone approved these changes

2018-12-04 13:08 UTC, merged