Lesson 6
Pekhov/TestGuru pull request #5
Opened 2018-12-05 06:47 UTC by Pekhov

2018-12-05 08:30 UTC, BubuntuClu requested changes

2018-12-05 08:30 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :simple, -> { where(level: 0..1) }
в этих скоупах ты можешь использовать уже определенный выше скоуп `by_level`

` scope :simple, -> { by_level(0..1) }`

2018-12-05 08:30 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :level, numericality: {only_integer: true, greater_than: 0}, uniqueness: true
если так сделать, то у тебя не может быть двух тестов одного уровня. это неправильно.
уникальность должна быть на паре значений title-level

2018-12-05 08:30 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :level, numericality: {only_integer: true, greater_than: 0}, uniqueness: true
так же надо индекс добавить на это в БД

2018-12-05 08:30 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add(:question_id) << err_msg if question.answers.count > 4
мне кажется, лучше использовать такой синтаксис `errors.add(:question_id, err_msg)`. в этом случае ты сможешь задать любое имя ключа для ошибки

2018-12-05 18:38 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :middle, -> { where(level: 2..4) }
в остальных скоупах тоже можно было заменить

2018-12-05 18:38 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true, uniqueness: true
`validates :title, presence: true, uniqueness: { scope: :level }`

2018-12-05 18:38 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :level, numericality: {only_integer: true, greater_than: 0}, uniqueness: true
` uniqueness: true` тут это надо убрать

2018-12-05 23:37 UTC, psylone requested changes

2018-12-05 23:37 UTC, psylone commented on app/models/answer.rb
> +    errors.add(:question_id, err_msg) if question.answers.count > 4
Если уже есть 4 ответа у вопроса, сможем создать 5-й, поскольку `4 > 4` вернёт `false`.

2018-12-05 23:37 UTC, psylone commented on app/models/test.rb
>      def tests_in_category(category)
Сделай скоуп метод.

2018-12-05 23:37 UTC, psylone commented on db/migrate/20181205161732_add_index_to_tests.rb
> +    add_index(:tests, [:title, :level], unique: true)
👍

2018-12-06 08:30 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :tests_in_category, ->(category) { joins(:category).where(categories: {title: category}).order(id: :asc).pluck(:title) }
сортировку и `pluck` не надо помещать в скоуп. скоуп должен возвращать `ActiveRecord::Relation`, чтобы мы могли всегда построить цепочку вызовов. метод надо оставить, но часть его реализации заменить на скоуп

2018-12-06 09:05 UTC, Pekhov commented on app/models/test.rb
> +  scope :tests_in_category, ->(category) { joins(:category).where(categories: {title: category}).order(id: :asc).pluck(:title) }
> сортировку и `pluck` не надо помещать в скоуп. скоуп должен возвращать `ActiveRecord::Relation`, чтобы мы могли всегда построить цепочку вызовов. метод надо оставить, но часть его реализации заменить на скоуп

Поправил

2018-12-06 10:18 UTC, psylone approved these changes

2018-12-06 10:18 UTC, psylone commented on app/models/test.rb
> +      tests_in_category(category).order(id: :asc).pluck(:title)
👍

2019-01-09 10:33 UTC, merged