Lesson 7
Pekhov/TestGuru pull request #6
Opened 2019-01-09 13:53 UTC by Pekhov

2019-01-09 15:08 UTC, BubuntuClu requested changes

2019-01-09 15:08 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = Question.create(body: params[:question][:body], test_id: params[:test_id])
`Question.create(body: params[:question][:body], test_id: params[:test_id])` это можно заменить на `Question.create(question_params)`

но тут еще смотри какая может быть штука, тебе может не поступить параметры с фронта и тогда у тебя будут пустые параметры для создания вопроса. надо сделать проверку сохранился ли у тебя объект в БД и в зависимости от этого уже выводить сообщение

2019-01-09 15:08 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions
добавь еще опцию `shallow: true`

2019-01-09 15:08 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_question
тебе надо находить вопрос не перед всеми действиями, а только перед некоторыми. у тебя тут сейчас даже ошибки падать будут, если ты так оставишь

2019-01-09 16:16 UTC, Pekhov commented on app/controllers/questions_controller.rb
> +    question = Question.create(body: params[:question][:body], test_id: params[:test_id])
> это можно заменить на `Question.create(question_params)`

Я специально от этого ушел, что бы не усложнять пока жизнь:)

2019-01-10 11:20 UTC, psylone requested changes

2019-01-10 11:20 UTC, psylone commented on config/routes.rb
> +  get '/questions/:id/destroy', to: 'questions#destroy'
Нет необходимости в отдельном роуте на удаление вопроса. Посмотри вывод `bin/rails routes`.

2019-01-10 11:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: 'Question not found'
Необходимо также возвращать верный HTTP статус ответа.

2019-01-10 11:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    test = Test.find(params[:test_id])
Это стоит поместить в обратный вызов.

2019-01-10 11:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: Question.find(params[:id]).body
Поиск вопроса тоже удобно поместить в обратный вызов. Понадобится при удалении вопроса.

2019-01-10 11:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    question = Question.create(body: params[:question][:body], test_id: params[:test_id])
```suggestion
    question = @test.questions.create(question_params)
```

2019-01-10 11:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    question = Question.create(body: params[:question][:body], test_id: params[:test_id])
Также поскольку `create` вызывается без `!` то в случае возникновения ошибки сохранения вернется корректный ответ, хотя объект не сохранится в базе.

2019-01-10 11:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: "Destroy question with id=#{params[:id]}"
После удаления объекта из базы он всё ещё доступен в памяти.

2019-01-10 11:20 UTC, psylone commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
`:test_id` здесь не нужен, будет лучше находить тест с помощью обратного вызова и работать с методом ассоциации объекта `@test` уже в самом методе контроллера.

2019-01-10 17:26 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = nil
тут Евгений имел в виду, что ты можешь сделать 
` render plain: "Destroy question with id=#{@question.id}"

зануление тут не надо делать. достаточно просто `destroy`.

2019-01-10 17:28 UTC, BubuntuClu commented on config/routes.rb
> +  #get '/questions/:id/destroy', to: 'questions#destroy'
удаляй, тебе все равно не понадобиться этот код. комментарии старайся не тащить в мастер

2019-01-10 17:30 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
```
question = @test.questions.new(question_params)

if question.save
 ....
else
 ...
end
```

2019-01-10 19:04 UTC, Pekhov commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
поправил

2019-01-10 19:05 UTC, Pekhov commented on config/routes.rb
> +  #get '/questions/:id/destroy', to: 'questions#destroy'
поправил

2019-01-10 19:05 UTC, Pekhov commented on app/controllers/questions_controller.rb
> +    @question = nil
поправил

2019-01-10 23:08 UTC, psylone approved these changes

2019-01-10 23:08 UTC, psylone commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
У тебя и `create`, и `save`, выше нужно только создавать объект в памяти без сохранения его в базе.

2019-01-10 23:08 UTC, psylone commented on app/controllers/questions_controller.rb
> +    response.body = 'Question not found'
Лучше через `render`, ему можно передать аргумент с кодом статуса ответа: https://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option

2019-01-16 13:26 UTC, merged