Lesson 9 Homework
Pekhov/TestGuru pull request #8
Opened 2019-01-23 10:50 UTC by Pekhov

2019-01-23 17:35 UTC, BubuntuClu commented on app/models/tests_passage.rb
> +    correct_questions ? correct_questions.to_f/test.questions.count.to_f*100 : 0
пробелы между операциями ставь, текст сливается, сложно понять выражение

2019-01-23 17:35 UTC, BubuntuClu commented on app/models/tests_passage.rb
> +  before_update :before_update_set_next_question
попробуй  `before_validation_set_first_question` и  `before_update_set_next_question` объединить в одну. валидация может быть не только на `create`

2019-01-23 17:35 UTC, BubuntuClu commented on app/views/tests_passages/result.html.erb
> +<% if result >= 85 %>
что такое 85? не понятно. логику во вьюху стараются не выносить. можешь весь этот код в хелпер вынести, а в хелпере вызывать метод модели `tests_passages`, который тебе вернет `true/false`. И уже в моделе ты можешь константу определить, которая будет хранить твое значение 85

2019-01-24 04:56 UTC, Pekhov commented on app/models/tests_passage.rb
> +  before_update :before_update_set_next_question
Получилось только второй строкой. В одну строку не получилось. Так не работает:
before_validation :before_validation_set_first_question, :before_update_set_next_question, on: %i[create update]

2019-01-24 05:20 UTC, Pekhov commented on app/views/tests_passages/result.html.erb
> +<% if result >= 85 %>
Вынес логику, но немного иначе.

2019-01-24 11:08 UTC, psylone commented on app/models/tests_passage.rb
> +  before_update :before_update_set_next_question
В этом случае не нужно `:on` указывать опцию. `create` и `update` это `save` а обратный вызов перед валидацией по умолчанию так и работает перед `save`.

2019-01-24 11:12 UTC, psylone requested changes

2019-01-24 11:12 UTC, psylone commented on app/helpers/tests_passages_helper.rb
> +    html = if PASS_VALUE >= 85
По сути, это логика отображения, её стоило оставить в шаблоне. То что касается определения того был ли успешно пройден тест можно определить в модели, включая метод `@test_passages.success?`, например.

2019-01-24 11:12 UTC, psylone commented on app/models/tests_passage.rb
> +    correct_questions ? correct_questions.to_f / test.questions.count.to_f * 100 : 0
`correct_question` по умаолчанию имеет значение `0`, значит условие всегда будет `true`.

2019-01-24 11:49 UTC, Pekhov commented on app/models/tests_passage.rb
> +    correct_questions ? correct_questions.to_f / test.questions.count.to_f * 100 : 0
Исправил

2019-01-24 11:49 UTC, Pekhov commented on app/helpers/tests_passages_helper.rb
> +    html = if PASS_VALUE >= 85
Исправил

2019-01-24 11:56 UTC, Pekhov commented on app/models/tests_passage.rb
> +  before_update :before_update_set_next_question
Да, но в данном случае set_first_question важно выполнять именно при создании и не нужно при обновлении, а set_next_question наоборот. Так что их в любом случае нужно разграничить.

2019-01-24 20:04 UTC, psylone commented on app/models/tests_passage.rb
> +  before_update :before_update_set_next_question
Как при создании, так и при обновлении будет вызываться `save`, а перед ним валидации. Здесь задачу можно сформулировать так: _установить следующий вопрос_ перед запуском валидаций объекта.

Есть момент что следующий вопрос будет устанавливаться при каждом обновлении (вызове `save`), в наших условиях это приемлемо.

2019-01-24 20:06 UTC, psylone approved these changes

2019-01-24 20:06 UTC, psylone commented on app/models/tests_passage.rb
> +    @result >= PASS_VALUE
Здесь нет необходимости в инстанс переменной. Лучше вынести подсчет в отдельный метод:

```ruby
def success?
  success_value >= PASS_VALUE
end
```

2019-01-24 20:06 UTC, psylone commented on app/models/tests_passage.rb
> +  PASS_VALUE = 85.freeze
`85` это singleton, `freeze` делать нет необходимости.

2019-01-24 20:06 UTC, psylone commented on app/views/tests_passages/result.html.erb
> +<% if @tests_passages.success? %>
👍

2019-01-25 07:57 UTC, merged