Lesson 10 Homework
Pekhov/TestGuru pull request #9
Opened 2019-01-25 10:22 UTC by Pekhov

2019-01-25 19:27 UTC, psylone requested changes

2019-01-25 19:27 UTC, psylone commented on app/controllers/tests_controller.rb
>    def find_user
Этот метод больше не нужен, вызывай сразу `current_user`.

2019-01-25 19:27 UTC, psylone commented on app/models/user.rb
> +  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: true }
Необходимо также добавить уникальный индекс в базе данных.

2019-01-25 19:27 UTC, psylone commented on app/controllers/application_controller.rb
> +    cookies[:path] = request.original_url
Где это используется?

2019-01-26 11:57 UTC, Pekhov commented on app/controllers/tests_controller.rb
>    def find_user
убрал

2019-01-26 12:00 UTC, Pekhov commented on app/models/user.rb
> +  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: true }
Добавил

2019-01-26 12:01 UTC, Pekhov commented on app/controllers/application_controller.rb
> +    cookies[:path] = request.original_url
Это 6 задание, используется в контроллере сессий:
if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to cookies[:path]

2019-01-26 17:18 UTC, psylone approved these changes

2019-01-26 17:18 UTC, psylone commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:path]
Может быть `nil` в `cookies[:path]`, поэтому `redirect_to cookies[:path] || root_path`.

2019-01-26 17:18 UTC, psylone commented on app/controllers/application_controller.rb
> +    cookies[:path] = request.original_url
Это понятно, не увидел просто изменения в пулл реквесте на тот момент.

2019-01-26 17:18 UTC, psylone commented on app/controllers/application_controller.rb
> +    cookies[:path] = request.original_url
Стоит устанавливать куку внутри условного выражения только для случая когда нет `current_user`.

2019-01-26 17:18 UTC, psylone commented on app/views/sessions/_form.html.erb
> +  <%= flash_messages %>
Удобно выводить флэш сообщения в главном шаблоне приложения, чтобы такие сообщения выводились для пользователя в едином месте.

2019-01-28 05:12 UTC, merged